name: test
on: [push]

jobs:
  io_test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Permission Setting
        run: chmod +x kadai4.sh test.sh
      - name: Test Run
        run: ./test.sh
